---
title: "long-term growth and composition only prop"
author: "Yan"
date: "2024-01-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Import data and lirabry 
```{r}
# Load necessary libraries
library(ggplot2)
library(matlib)

# Read the CSV files
a <- read.csv("data/areal_circ_even.csv", row.names=1)


# Extracting values from the 'a' data frame
# areal percentage
JGJ <- a["GJ", "J"]
JGI <- a["GI", "J"]
JGC <- a["GC", "J"]
JSJ <- a["SJ", "J"]
JSI <- a["SI", "J"]
JSC <- a["SC", "J"]
JFiJ <- a["FiJ", "J"]
JFiI <- a["FiI", "J"]
JFiC <- a["FiC", "J"]
JFuJ <- a["FuJ", "J"]
JFuI <- a["FuI", "J"]
JFuC <- a["FuC", "J"]
JMJ <- a["mort", "J"]
JRJ <- a["rec", "J"]

IGJ <- a["GJ", "I"]
IGI <- a["GI", "I"]
IGC <- a["GC", "I"]
ISJ <- a["SJ", "I"]
ISI <- a["SI", "I"]
ISC <- a["SC", "I"]
IFiJ <- a["FiJ", "I"]
IFiI <- a["FiI", "I"]
IFiC <- a["FiC", "I"]
IFuJ <- a["FuJ", "I"]
IFuI <- a["FuI", "I"]
IFuC <- a["FuC", "I"]
IMI <- a["mort", "I"]
IRJ <- a["rec", "I"]

CGJ <- a["GJ", "C"]
CGI <- a["GI", "C"]
CGC <- a["GC", "C"]
CSJ <- a["SJ", "C"]
CSI <- a["SI", "C"]
CSC <- a["SC", "C"]
CFiJ <- a["FiJ", "C"]
CFiI <- a["FiI", "C"]
CFiC <- a["FiC", "C"]
CFuJ <- a["FuJ", "C"]
CFuI <- a["FuI", "C"]
CFuC <- a["FuC", "C"]
CMC <- a["mort", "C"]
CRJ <- a["rec", "C"]

```

```{r}
# calculate Transition matrix

# Fate of Juvs
mJJ <- JGJ + JSJ + JFiJ + JFuJ
mJI <- JGI + JSI + JFuI + JFiI
mJC <- JGC + JSC + JFiC + JFuC

# Fate of irregular adults 
mIJ <- ISJ + IFuJ + IFiJ + IRJ
mII <- IGI + ISI + IFuI + IFiI
mIC <- IGC + ISC + IFuC + IFiC

# Fate of compact adults 
mCJ <- CSJ + CFiJ + CFuJ + CRJ
mCI <- CGI + CSI + CFuI + CFiI
mCC <- CGC + CSC + CFuC + CFiC

# Transition matrix
mx_L <- matrix(c(mJJ, mIJ, mCJ, 
              mJI, mII, mCI, 
              mJC, mIC, mCC), 3, 3, byrow=TRUE)

lam <- Re(eigen(mx_L)$values[1])

# Print the matrix
print(mx_L)
print(lam)

```

```{r}
# Calculate sensitivity and elasticity

w <- eigen(mx_L)$vectors  # right eigen vectors
v <- Conj(solve(w))    # complex conjugate of left eigen vectors

#Calculate sensitivity matrix  
senmat <- Re(v[1,] %*% t(w[,1])) 

#Calculate elasticity matrix
emat <- (1/(Re(eigen(mx_L)$values[1]))) * senmat * mx_L


round(senmat,2) 
round(emat,2)

```

