---
title: "Outlet NMMBA project"
author: "Yan"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
####LIBRARIES####
library(tidyverse)
library(readr)
```

```{r data import, echo=TRUE, results='hide', include=FALSE}
####DATA####
pa_data <- read_csv("OL_PA_all.csv")

####CLASS CHECK####
pa_data$Shape_Length <- as.numeric(pa_data$Shape_Length)
pa_data$Shape_Area <- as.numeric(pa_data$Shape_Area)
pa_data$Survey_times <- as.numeric(pa_data$Survey_times)
pa_data$Plot_ID <- as.factor(pa_data$Plot_ID)
#pa_data$Source <- as.factor(pa_data$Source)
pa_data$Fate <- as.factor(pa_data$Fate)
pa_data$Recruit[is.na(pa_data$Recruit)] <- "N" #fill the data with NO recruit
pa_data$Recruit <- as.factor(pa_data$Recruit)
summary(pa_data)
#head(pa_data)
```

```{r check ID replicate or not}
data_test <- dplyr::filter(pa_data, Survey_times == 3 & Plot_ID == "M1")
which(duplicated(data_test$ID)) # Find replicate index
#data_test$ID[8]
```


```{r}
#measure GCP error
GCP_data <- read_csv("GCP.csv")
GCP_data$Time <- as.factor(GCP_data$Time)

ggplot(GCP_data, aes(x=Time,y=Shape_Area,color=Site))+
  geom_point()

ggplot(GCP_data, aes(x=Time,y=Shape_Area))+
  geom_boxplot()+
  geom_hline(yintercept = 0.12*0.12,color="red")

GCP_error <- data.frame(Time=c("1","2","3"))

for(t in 1:3){
  GCP_error[t,"mean"] <- mean(GCP_data$Shape_Area[GCP_data$Time==t])
  GCP_error[t,"SD"] <- sd(GCP_data$Shape_Area[GCP_data$Time==t])
  GCP_error[t,"error"] <- (GCP_error$mean[t] - 0.12*0.12)/GCP_error$mean[t]*100
  GCP_error[t,"N"] <- sum(GCP_data$Time==t)
}

```


```{r data classify, echo=TRUE, results='hide', include=FALSE}
####Classify juvenile and adult####
pa_data$size_class[pa_data$Shape_Area<=0.002827433 ] <- 'J' #size smaller than 6 cm is juvenile
pa_data$size_class[pa_data$Shape_Area > 0.002827433] <- 'A'
pa_data$size_class <- as.factor(pa_data$size_class)

####Calculate pa_ratio####
pa_data$pa_ratio <- pa_data$Shape_Length / pa_data$Shape_Area
####Classify irregular and compact adult####
levels(pa_data$size_class) <- c(levels(pa_data$size_class), "IA", "CA")
pa_data$size_class[pa_data$pa_ratio<40 & pa_data$size_class=='A'] <- 'CA'
pa_data$size_class[pa_data$pa_ratio>=40 & pa_data$size_class=='A'] <- 'IA'

####Classify medium and large adult####
pa_data$pure_size[pa_data$Shape_Area<=0.002827433 ] <- 'S' #size smaller than 6 cm is juvenile
pa_data$pure_size[pa_data$Shape_Area>0.002827433 & pa_data$Shape_Area<= 0.06*0.06*pi] <- 'M'
pa_data$pure_size[pa_data$Shape_Area> 0.06*0.06*pi] <- 'L'
pa_data$pure_size <- as.factor(pa_data$pure_size)
pa_data$pure_size <- factor(pa_data$pure_size, levels = c("S","M","L"))

summary(pa_data)



```


```{r plot definition of J IA CA}
pa_data$Circle_Length <- sqrt(pa_data$Shape_Area / pi) * 2 * pi
pa_data$circ <- pa_data$Circle_Length / pa_data$Shape_Length

pa_data$size_class_circ <- NA
pa_data$size_class_circ[pa_data$Shape_Area <= 0.002827433] <- "J"

cutoff <- median(pa_data$circ[pa_data$size_class != "J"])
pa_data$size_class_circ[pa_data$Shape_Area > 0.002827433 & pa_data$circ >= cutoff] <- "CA"
pa_data$size_class_circ[pa_data$Shape_Area > 0.002827433 & pa_data$circ < cutoff] <- "IA"

#calculate size half half
cutoff_s <- median(pa_data$Shape_Area[pa_data$size_class != "J"])
pa_data$size_class_size <- NA
pa_data$size_class_size[pa_data$Shape_Area <= 0.002827433] <- "J"
pa_data$size_class_size[pa_data$Shape_Area > 0.002827433 & pa_data$Shape_Area >= cutoff_s] <- "L"
pa_data$size_class_size[pa_data$Shape_Area > 0.002827433 & pa_data$Shape_Area < cutoff_s] <- "M"
pa_data$size_class_size <- as.factor(pa_data$size_class_size)
pa_data$size_class_size <- factor(pa_data$size_class_size, levels = c("J","M","L"))

####Plot pa_ratio with size base on morphological stages####
#data_p1 = filter(pa_data, Survey_times == 3)

plot(log10(pa_data$Shape_Area), (pa_data$circ),
     pch = 10,
     col = factor(pa_data$size_class_circ))
abline(v=log10(pi*0.03^2))#check the standard of adult
abline(h=log10(40)) #check the standard of compact adult

# Calculate number of J, IA, CA 
count_J <- sum(grepl("J", pa_data$size_class))
count_IA <- sum(grepl("IA", pa_data$size_class))
count_CA <- sum(grepl("CA", pa_data$size_class))
pa_data$size_class <- factor(pa_data$size_class, levels = c("J","IA","CA"))

# Calculate number of J, IA, CA 
count_J_c <- sum(grepl("J", pa_data$size_class_circ))
count_IA_c <- sum(grepl("IA", pa_data$size_class_circ))
count_CA_c <- sum(grepl("CA", pa_data$size_class_circ))

pa_data$size_class_circ <- as.factor(pa_data$size_class_circ)
pa_data$size_class_circ <- factor(pa_data$size_class_circ, levels = c("J","IA","CA"))


#Classify ultimate P/A ratio -> CA need to be both large and compact
pa_data$pa_ratio_x <- NA
pa_data$pa_ratio_x[pa_data$pure_size == "L" & pa_data$size_class_circ == "CA"]  <- "CA"
pa_data$pa_ratio_x[pa_data$pure_size == "S" & pa_data$size_class_circ == "J"]  <- "J"
pa_data$pa_ratio_x[is.na(pa_data$pa_ratio_x)] <- "IA"
pa_data$pa_ratio_x <- as.factor(pa_data$pa_ratio_x)
pa_data$pa_ratio_x <- factor(pa_data$pa_ratio_x, levels = c("J","IA","CA"))

pa_data$pa_ratio_xx <- NA
pa_data$pa_ratio_xx[pa_data$size_class_size == "L" & pa_data$size_class_circ == "CA"]  <- "CA"
pa_data$pa_ratio_xx[pa_data$size_class_size == "J" & pa_data$size_class_circ == "J"]  <- "J"
pa_data$pa_ratio_xx[is.na(pa_data$pa_ratio_xx)] <- "IA"
pa_data$pa_ratio_xx <- as.factor(pa_data$pa_ratio_xx)
pa_data$pa_ratio_xx <- factor(pa_data$pa_ratio_xx, levels = c("J","IA","CA"))




#GLM logestic regression , binomial, Fate 0 1
```

```{r}
#design PA ratio

#Median_P <- median(pa_data$Shape_Length[pa_data$size_class != "J"])
#Median_A <- median(pa_data$Shape_Area[pa_data$size_class != "J"])
#M_PA_ratio <- Median_P / Median_A
cutoff_pa <- median(pa_data$pa_ratio[pa_data$size_class != "J"])
pa_data$size_class_pa <- NA
pa_data$size_class_pa[pa_data$Shape_Area <= 0.002827433] <- "J"
pa_data$size_class_pa[pa_data$Shape_Area > 0.002827433 & pa_data$pa_ratio >= cutoff_pa] <- "IA"
pa_data$size_class_pa[pa_data$Shape_Area > 0.002827433 & pa_data$pa_ratio < cutoff_pa] <- "CA"
pa_data$size_class_pa <- as.factor(pa_data$size_class_pa)
pa_data$size_class_pa <- factor(pa_data$size_class_pa, levels = c("J","IA","CA"))


```



```{r plot J IA CA composition}
p1 = ggplot(data = pa_data, aes(x = Survey_times, fill = size_class,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("Survey_times") + 
  ylab("Proportion of colonies") 
p1

p1_c = ggplot(data = pa_data, aes(x = Survey_times, fill = size_class_circ,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("Survey_times") + 
  ylab("Proportion of colonies") 
p1_c



# how to add the number of N?

```


```{r plot J IA CA composition by area}
p1 = ggplot(data = pa_data, aes(x = Survey_times, y= Shape_Area, fill = pure_size,na.rm = TRUE)) + 
  geom_bar(position = "fill", stat = "identity") +
  xlab("Survey_times") + 
  ylab("Proportion of Area") 
p1


```


```{r}
####Add Fate (G,S) and their sa_change####
pa_data_GS <- data.frame()
# Subset the data.frame to only include observations from the two dates of interest
for (plot_id in c("M1", "M2", "TY3")) { # loop in sites
  #print(plot_id)
  for (t in 1:2) { # loop in survey times
    #print(paste0("t=",t))
    pa_data_subset <- pa_data[pa_data$Plot_ID == plot_id,]
    pa_data_subset <- pa_data_subset[pa_data_subset$Survey_times == t | pa_data_subset$Survey_times == t+1, ]
    pa_data_subset <- pa_data_subset[!(pa_data_subset$Fate %in% c("D","Fu","Fi") & pa_data_subset$Survey_times == t), ]
    pa_data_subset <- pa_data_subset[!(pa_data_subset$Recruit == "Y"& pa_data_subset$Survey_times == t+1),] #don't calculate new colonies
    pa_data_subset <- pa_data_subset[!(!is.na(pa_data_subset$Source) & pa_data_subset$Survey_times == t+1),]
    
    # Create a new data.frame to store the area change for each coral colony
    area_change_df <- data.frame(ID = unique(pa_data_subset$ID), sa_change = NA)
    
    # Loop through each ID and calculate the area change between the two dates
    for (i in 1:length(unique(pa_data_subset$ID))) {
      #print(paste0("i=",i))
      current_id <- unique(pa_data_subset$ID)[i]
      current_area <- pa_data_subset[pa_data_subset$ID == current_id & pa_data_subset$Survey_times == t, "Shape_Area"]
      future_area <- pa_data_subset[pa_data_subset$ID == current_id & pa_data_subset$Survey_times == t+1, "Shape_Area"]
      # Check if current_area and future_area are not NA
      if (nrow(current_area) > 0 & nrow(future_area) > 0) {
        area_change <- future_area - current_area
        area_change_df[i, "sa_change"] <- area_change
      }
    }
    pa_data_subset <- pa_data_subset[pa_data_subset$Survey_times == t,] #only left t to merge
    # Merge the area change data.frame back into the original data.frame using the ID variable
    pa_data_subset$sa_change <- area_change_df$sa_change[match(pa_data_subset$ID, area_change_df$ID)]
    pa_data_GS <- rbind(pa_data_GS, pa_data_subset)
    }
}

#Calculate for growth and shrink
pa_data_GS$Fate <- ifelse(pa_data_GS$sa_change >= 0, "G", "S")
```


```{r}
###Add sa_change of D ####
pa_data_D <- data.frame()

# Calculate sa_change
for (plot_id in c("M1", "M2", "TY3")) {
  for (t in 1:2) {
    # Subset the data.frame to only include D and N colonies
    pa_data_subset <- pa_data[pa_data$Plot_ID == plot_id,]
    pa_data_subset <- pa_data_subset[pa_data_subset$Survey_times == t, ]
    pa_data_subset <- pa_data_subset[pa_data_subset$Fate == "D", ]
    pa_data_subset <- pa_data_subset[complete.cases(pa_data_subset$ID), ] # clean NA rows
    
    # Create a new data.frame to store the area change for each coral colony
    area_change_df <- data.frame(ID = unique(pa_data_subset$ID), sa_change = NA)

    # Loop through each ID and calculate the area change between the two dates
    for (i in 1:length(unique(pa_data_subset$ID))) {
      #print(paste0("i=",i))
      current_id <- unique(pa_data_subset$ID)[i]
      # Calculate D 
        area_change <- 0 - pa_data_subset$Shape_Area[i] # calculate Dead sa_change
        area_change_df[i, "sa_change"] <- area_change
    }
    pa_data_subset$sa_change <- area_change_df$sa_change[match(pa_data_subset$ID, area_change_df$ID)]
    pa_data_D <- rbind(pa_data_D, pa_data_subset) #Bind subset into DN dataframe
}
}

```



```{r}
###Add sa_change of Fi####
pa_data_Fi <- data.frame()

for (plot_id in c("M1", "M2", "TY3")) {
  for (t in 1:2) {
# Subset the data.frame to only include Fi colonies
    pa_data_subset <- pa_data[pa_data$Plot_ID == plot_id,]
    pa_data_subset <- pa_data_subset[pa_data_subset$Survey_times == t | pa_data_subset$Survey_times == t+1, ]
    pa_data_subset <- pa_data_subset[(pa_data_subset$Fate == "Fi" & pa_data_subset$Survey_times == t) | (!is.na(pa_data_subset$Source) & pa_data_subset$Survey_times == t+1), ]
    pa_data_subset <- pa_data_subset[complete.cases(pa_data_subset$ID), ] # clean NA rows

    pa_data_subset_1 <- pa_data_subset[pa_data_subset$Survey_times == t,] # time one data
    pa_data_subset_2 <- pa_data_subset[pa_data_subset$Survey_times == t+1,] # time two data
    
    if (nrow(pa_data_subset_1) != 0){  # check there are fi colonies or not
    # Get the ID of fission colonies
      area_change_df <- data.frame(ID = unique(pa_data_subset_1$ID), sa_change = NA)
    # Loop through Fi colonies dataframe
    for (j in 1:length(unique(pa_data_subset_1$ID))) {
      current_id_1 <- unique(pa_data_subset_1$ID)[j]
    # Loop through each ID and calculate total Fi from t+1
    Fi_total <- 0
      for (i in 1:length(unique(pa_data_subset_2$ID))) {
      #print(paste0("i=",i))
      current_id <- unique(pa_data_subset_2$ID)[i]
      # Calculate Fi
      if (pa_data_subset_2$Source[i] == current_id_1) {
      Fi_total <- Fi_total + pa_data_subset_2$Shape_Area[i] # calculate total Fi area from single colony
      }
    }
      area_change <- Fi_total - pa_data_subset_1$Shape_Area[j]
      area_change_df[j, "sa_change"] <- area_change
    }
    pa_data_subset_1$sa_change <- area_change_df$sa_change[match(pa_data_subset_1$ID, area_change_df$ID)]
    pa_data_Fi <- rbind(pa_data_Fi, pa_data_subset_1) #Bind subset into Fi dataframe
    }
  }
  }
    
```

```{r}
###Add sa_change of Fu####
pa_data_Fu <- data.frame()

for (plot_id in c("M1", "M2", "TY3")) {
  for (t in 1:2) {
# Subset the data.frame to only include Fu colonies
    pa_data_subset <- pa_data[pa_data$Plot_ID == plot_id,]
    pa_data_subset <- pa_data_subset[pa_data_subset$Survey_times == t | pa_data_subset$Survey_times == t+1, ]
    pa_data_subset <- pa_data_subset[(pa_data_subset$Fate == "Fu" & pa_data_subset$Survey_times == t) | (!is.na(pa_data_subset$Source) & pa_data_subset$Survey_times == t+1), ]
    pa_data_subset <- pa_data_subset[complete.cases(pa_data_subset$ID), ] # clean NA rows

    pa_data_subset_1 <- pa_data_subset[pa_data_subset$Survey_times == t,] # time one data
    pa_data_subset_1$ID <- as.numeric(pa_data_subset_1$ID)
    pa_data_subset_2 <- pa_data_subset[pa_data_subset$Survey_times == t+1,] # time two data
    pa_data_subset_2$Source <- as.character(pa_data_subset_2$Source)
    pa_data_subset_2 <- pa_data_subset_2[grepl("\\+", pa_data_subset_2$Source) == TRUE,] # remove Fi
    
    ##Calculate total source area from subset2 first##
    if (nrow(pa_data_subset_2) != 0){  # check there are fu colonies or not
    # Get the ID of Fusion colonies
      Source_total <- data.frame(ID = unique(pa_data_subset_2$ID), Source_total = NA)
    # Loop through Time2 colonies dataframe
    for (j in 1:length(unique(pa_data_subset_2$ID))) {
    # break source into separate IDs
      Fu_list <- strsplit(as.character(pa_data_subset_2$Source)[j], "\\+")[[1]] # separate numbers
      Fu_list <- as.numeric(Fu_list)
   # Loop through each ID and calculate total Fi from t+1
    Fu_total <- 0
      for (i in 1:length(unique(pa_data_subset_1$ID))) {
      #print(paste0("i=",i))
        if ((pa_data_subset_1$ID)[i] %in% Fu_list){ #check the Fu ID match or not
          Fu_total <- Fu_total + pa_data_subset_1$Shape_Area[i] # calculate total Fu area 
        } 
    }
      Source_total[j, "Source_total"] <- Fu_total
    }
      pa_data_subset_2$Source_total <- Source_total$Source_total[match(pa_data_subset_2$ID, Source_total$ID)]
    }
    
    ##Calculate sa_change in subset1##
    if (nrow(pa_data_subset_1) != 0){  # check there are fi colonies or not
    # Get the ID of fission colonies
      area_change_df <- data.frame(ID = unique(pa_data_subset_1$ID), sa_change = NA)
    # Loop through Fu colonies dataframe
    for (j in 1:length(unique(pa_data_subset_1$ID))) {
      current_id <- unique(pa_data_subset_1$ID)[j]
    # Loop through each ID in T2 data and find total Fu area
      for (i in 1:length(unique(pa_data_subset_2$ID))) {
      #print(paste0("i=",i))
      # break source into separate IDs
      Fu_list <- strsplit(as.character(pa_data_subset_2$Source)[i], "\\+")[[1]] # separate numbers
      Fu_list <- as.numeric(Fu_list)
      # Calculate Fu area change
      if (current_id %in% Fu_list) {
        proportion <- (pa_data_subset_1$Shape_Area[j] / pa_data_subset_2$Source_total[i])
        area_change <- pa_data_subset_2$Shape_Area[i]*proportion - pa_data_subset_1$Shape_Area[j]
      }
    }
      area_change_df[j, "sa_change"] <- area_change
    }
    pa_data_subset_1$sa_change <- area_change_df$sa_change[match(pa_data_subset_1$ID, area_change_df$ID)]
    pa_data_Fu <- rbind(pa_data_Fu, pa_data_subset_1) #Bind subset into Fu dataframe
    }
  }
  }
```


```{r}
####Combine all of cleaned data####
pa_data_done <- rbind(pa_data_GS,pa_data_D,pa_data_Fi,pa_data_Fu)
#pa_data_12 <- filter(pa_data, Survey_times == 1 | Survey_times == 2)

# ## Adjust the sa_change base on the proportion of Time (Months)
# pa_data_done$sa_change_ad <-  ifelse(pa_data_done$Survey_times == 1 & pa_data_done$Plot_ID == "M1",
#                                     pa_data_done$sa_change * 12/17,
#                                     ifelse(
#                                     pa_data_done$Survey_times == 2 & pa_data_done$Plot_ID == "M1",
#                                     pa_data_done$sa_change * 12/9,
#                                     ifelse(
#                                     pa_data_done$Survey_times == 1 & pa_data_done$Plot_ID == "M2",
#                                     pa_data_done$sa_change * 12/15,
#                                     ifelse(
#                                     pa_data_done$Survey_times == 2 & pa_data_done$Plot_ID == "M2",
#                                     pa_data_done$sa_change * 12/11,
#                                     ifelse(
#                                     pa_data_done$Survey_times == 1 & pa_data_done$Plot_ID == "TY3",
#                                     pa_data_done$sa_change * 12/18,
#                                     ifelse(
#                                     pa_data_done$Survey_times == 2 & pa_data_done$Plot_ID == "TY3",
#                                     pa_data_done$sa_change * 12/8,
#                                     pa_data_done$sa_change
#                                     )
#                                     )
#                                     )
#                                     )
#                                     )
# )


#### Calculate changing rate
pa_data_done$change_rate <- (pa_data_done$Shape_Area+pa_data_done$sa_change) / pa_data_done$Shape_Area

# # Calculate adjusted changing rate
# pa_data_done$change_rate_ad <- (pa_data_done$Shape_Area+pa_data_done$sa_change_ad) / pa_data_done$Shape_Area

# Bind time 3 data
pa_data_done <- bind_rows(list(pa_data_done,pa_data[pa_data$Survey_times == 3,]))

```



```{r plot}
####Plot pa_ratio and changing rate D=0 G>1####


#Filter date 
pa_data_done_12 = filter(pa_data_done, Survey_times == 1 | Survey_times == 2)

# plot pa_ratio and change rate in continuous
plot(pa_data_done_12$pa_ratio, pa_data_done_12$change_rate)


# plot pa_ratio and change rate in discrete (G=1, D=0)
pa_data_done$Discrete_change <- ifelse(pa_data_done$Fate == "D", 0, ifelse(pa_data_done$Fate == "G", 1, NA))
plot(pa_data_done_12$pa_ratio,pa_data_done_12$Discrete_change)
pa_data_done_12 = filter(pa_data_done, (Survey_times == 1 | Survey_times == 2) & size_class != "J") # remove Juvenile which have both high D and G
plot(pa_data_done_12$pa_ratio,pa_data_done_12$Discrete_change)

###plot a fit curve: pa_ratio vs change
# remove juvenile due to its both high G and D
pa_data_done_12 = filter(pa_data_done_12, size_class != "J")
p <- ggplot(data = pa_data_done_12, aes(pa_ratio,Discrete_change))+
  geom_point(shape=21)+
  geom_smooth(method="lm")
p



mod <- glm(Discrete_change ~ pa_ratio, family=binomial, data=pa_data_done_12)
summary(mod)

# Add a fit curve
fit <- lm(Discrete_change ~ poly(pa_ratio,1,raw=TRUE), data = pa_data_done_12)
cf <- coef(fit)
slope <- cf[2]
x_axis <- pa_data_done_12$pa_ratio
#plot(pa_data_done_12$pa_ratio, pa_data_done_12$Discrete_change)
#lines(x_axis, predict(fit, newdata = data.frame(pa_ratio = x_axis)))

```

```{r}
###plot a fit curve: size vs change
pa_data_done_12 = filter(pa_data_done_12, size_class != "J")
p <- ggplot(data = pa_data_done_12, aes(Shape_Area,Discrete_change))+
  geom_point(shape=21)+
  geom_smooth(method="lm")
p

```


```{r plot the Fate from J, IA, CA}
p2 = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = size_class, fill = Fate,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("size_class") + 
  ylab("Proportion of Fates")+
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
    stat="count",
    position=position_fill(vjust=0.5))
p2

p2_c = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = size_class_circ, fill = Fate,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("size_class_circ") + 
  ylab("Proportion of Fates")+
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
    stat="count",
    position=position_fill(vjust=0.5))
p2_c

p2_s = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = pure_size, fill = Fate,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("pure_size") + 
  ylab("Proportion of Fates")+
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
    stat="count",
    position=position_fill(vjust=0.5))
p2_s

# p2_x = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = pa_ratio_x, fill = Fate,na.rm = TRUE)) + 
#   geom_bar(position = "fill") +
#   xlab("pa_ratio_x") + 
#   ylab("Proportion of Fates")+
#   geom_text(
#     aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
#     stat="count",
#     position=position_fill(vjust=0.5))
# p2_x

# p2_xx = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = pa_ratio_xx, fill = Fate,na.rm = TRUE)) + 
#   geom_bar(position = "fill") +
#   xlab("pa_ratio_xx") + 
#   ylab("Proportion of Fates")+
#   geom_text(
#     aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
#     stat="count",
#     position=position_fill(vjust=0.5))
# p2_xx

p2_pa = ggplot(filter(pa_data_done, Survey_times == 1 | Survey_times == 2), aes(x = size_class_pa, fill = Fate,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("size_class_pa") + 
  ylab("Proportion of Fates")+
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
    stat="count",
    position=position_fill(vjust=0.5))
p2_pa

```


```{r}
### Fi and Fu increase or decrease area

#Filter date 
pa_data_done_12 <- filter(pa_data_done, Survey_times == 2 |Survey_times == 1)
pa_data_done_12 <- filter(pa_data_done_12, Fate == "Fi" | Fate == "Fu")
# Count the number of total Fi Fu
count_Fi <- sum(grepl("Fi", pa_data_done_12$Fate))
count_Fu <- sum(grepl("Fu", pa_data_done_12$Fate))

#Calculate for growth and shrink in Fi Fu
pa_data_done_12$FiFu_GS <- ifelse(pa_data_done_12$sa_change >= 0, "G", "S")

p2 = ggplot(pa_data_done_12, aes(x = Fate, fill = FiFu_GS,na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  xlab("Fates") + 
  ylab("Proportion of Fates")+
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=2)),
    stat="count",
    position=position_fill(vjust=0.5))

p2

# mean change rate of each dunamics
Fi_G <- filter(pa_data_done_12, Fate =="Fi" & FiFu_GS == "G")
Fi_G <- mean(Fi_G$change_rate )
Fi_S <- filter(pa_data_done_12, Fate =="Fi" & FiFu_GS == "S")
Fi_S <- mean(Fi_S$change_rate )
Fu_G <- filter(pa_data_done_12, Fate =="Fu" & FiFu_GS == "G")
Fu_G <- mean(Fu_G$change_rate )
Fu_S <- filter(pa_data_done_12, Fate =="Fu" & FiFu_GS == "S")
Fu_S <- mean(Fu_S$change_rate )


```

```{r}
### Calculate dynamics between three stages ###

dynamics_df <- data.frame()

## Find out how many J become IA and CA
for (plot_id in c("M1", "M2", "TY3")) {
  for (t in 1:2) {
#Filter date 
pa_data_subset <- pa_data_done[pa_data_done$Plot_ID == plot_id,]
pa_data_done_1 <- filter(pa_data_subset, Survey_times == t)
pa_data_done_2 <- filter(pa_data_subset, Survey_times == t+1)

# create a dataframe store morphological dynamic (ex. J Fu to CA = JFuCA)
morpho_dynamic <- data.frame(ID = unique(pa_data_done_1$ID),dynamic = NA, stage = NA, change_ratio = NA)

for (j in 1:length(unique(pa_data_done_1$ID))) {
      current_id <- unique(pa_data_done_1$ID)[j]
    # Loop through each ID in T2 data and find corresponding size class 
      for (i in 1:length(unique(pa_data_done_2$ID))) {
          # Combine the size class in different times and the caused fate
          if (pa_data_done_1$Fate[j] == "S" | pa_data_done_1$Fate[j] == "G"){
            if (current_id == pa_data_done_2$ID[i]){ # check the ID is match
              morpho_dynamic$stage[j] <- as.character(pa_data_done_1$size_class[j])
              morpho_dynamic$dynamic[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$size_class[i])
              morpho_dynamic$dynamic_p[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$pure_size[i])
              morpho_dynamic$change_ratio[j] <- pa_data_done_1$change_rate[j]
              morpho_dynamic$area[j] <- pa_data_done_1$Shape_Area[j]
              morpho_dynamic$sa_change[j] <- pa_data_done_1$sa_change[j]
              #morpho_dynamic$change_rate_ad[j] <- pa_data_done_1$change_rate_ad[j]
            } 
          } else if (pa_data_done_1$Fate[j] == "Fu"){
      # break source into separate IDs
      Fu_list <- strsplit(as.character(pa_data_done_2$Source)[i], "\\+")[[1]] 
      Fu_list <- as.numeric(Fu_list)
            if (current_id %in% Fu_list){
              morpho_dynamic$stage[j] <- as.character(pa_data_done_1$size_class[j])
              morpho_dynamic$dynamic[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$size_class[i])
              morpho_dynamic$dynamic_p[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$pure_size[i])
              morpho_dynamic$change_ratio[j] <- pa_data_done_1$change_rate[j]
              morpho_dynamic$area[j] <- pa_data_done_1$Shape_Area[j]
              morpho_dynamic$sa_change[j] <- pa_data_done_1$sa_change[j]
              #morpho_dynamic$change_rate_ad[j] <- pa_data_done_1$change_rate_ad[j]
            }
          } else if (pa_data_done_1$Fate[j] == "Fi") { ###CHeck
            current_id <- as.character(current_id)
          if (current_id == pa_data_done_2$Source[i] & !is.na(pa_data_done_2$Source[i])){ # check the ID is match
            morpho_dynamic$stage[j] <- as.character(pa_data_done_1$size_class[j])
              morpho_dynamic$dynamic[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$size_class[i])
              morpho_dynamic$dynamic_p[j] <- paste0(pa_data_done_1$Fate[j],pa_data_done_2$pure_size[i])
              indices <- which(pa_data_done_2$Source %in% pa_data_done_1$ID[j])
              Fi_total <- sum(pa_data_done_2$Shape_Area[indices])
              morpho_dynamic$change_ratio[j] <- pa_data_done_1$change_rate[j]
              morpho_dynamic$area[j] <- pa_data_done_1$Shape_Area[j]
              morpho_dynamic$sa_change[j] <- pa_data_done_1$sa_change[j]
              #morpho_dynamic$change_rate_ad[j] <- pa_data_done_1$change_rate_ad[j]
            }
          } else if (pa_data_done_1$Fate[j] == "D") {
            morpho_dynamic$stage[j] <- as.character(pa_data_done_1$size_class[j])
          morpho_dynamic$dynamic[j] <- "D"
          morpho_dynamic$dynamic_p[j] <- "D"
          morpho_dynamic$change_ratio[j] <- pa_data_done_1$change_rate[j]
          morpho_dynamic$area[j] <- pa_data_done_1$Shape_Area[j]
          morpho_dynamic$sa_change[j] <- pa_data_done_1$sa_change[j]
          #morpho_dynamic$change_rate_ad[j] <- pa_data_done_1$change_rate_ad[j]
        }
    }
    }
morpho_dynamic$Survey_times <- t
morpho_dynamic$Site <- plot_id
morpho_dynamic$pure_size <- pa_data_done_1$pure_size #add pure_size
dynamics_df <- rbind(dynamics_df, morpho_dynamic)
  }
}

```

```{r}
dynamics_df_1 <- filter(dynamics_df)
### Plot proportion of morphological dynamics
p2 = ggplot(data = subset(dynamics_df_1, !is.na(dynamic)), aes(x = factor(stage,levels = c("J","IA","CA")), fill = dynamic, na.rm = TRUE)) + 
  geom_bar(position = "fill") +
  geom_text(
    aes(label=signif(..count.. / tapply(..count.., ..x.., sum)[as.character(..x..)], digits=3)),
    stat="count",
    position=position_fill(vjust=0.5))+
  xlab("Stage") + 
  ylab("Proportion of colonies") 
p2



```

```{r}
### Calculate mean change ratio in each stage
# dynamics_df_J <- filter(dynamics_df, stage == "J" )
# dynamics_df_IA <- filter(dynamics_df, stage == "IA" )
# dynamics_df_CA <- filter(dynamics_df, stage == "CA" )
# 
# change_ratio_J <- dynamics_df_J %>% 
#   group_by(dynamic) %>% 
#   summarize(mean_x = mean(change_rate_ad), count = n())
# 
# change_ratio_IA <- dynamics_df_IA %>% 
#   group_by(dynamic) %>% 
#   summarize(mean_x = mean(change_rate_ad))
# 
# change_ratio_CA <- dynamics_df_CA %>% 
#   group_by(dynamic) %>% 
#   summarize(mean_x = mean(change_rate_ad))
```

```{r}
#Calculate ratio and consider the proportion of time
# change_ratio_df <- data.frame()
# 
# for (ID in c("M1","M2","TY3")) {
#   for (t in 1:2) {
# dynamics_df_J <- filter(dynamics_df, stage == "J", Survey_times == t)
# dynamics_df_J <- dynamics_df_J[dynamics_df_J$Site == ID,]
# dynamics_df_IA <- filter(dynamics_df, stage == "IA" & Survey_times == t)
# dynamics_df_IA <- dynamics_df_IA[dynamics_df_IA$Site == ID,]
# dynamics_df_CA <- filter(dynamics_df, stage == "CA" & Survey_times == t)
# dynamics_df_CA <- dynamics_df_CA[dynamics_df_CA$Site == ID,]
# 
# change_ratio_J <- dynamics_df_J %>% 
#   group_by(dynamic) %>% 
#   summarize(ratio = mean(change_ratio))
# change_ratio_J$Site <- ID
# change_ratio_J$Survey_time <- t
# change_ratio_J$Stage <- "J"
# 
# change_ratio_IA <- dynamics_df_IA %>% 
#   group_by(dynamic) %>% 
#   summarize(ratio = mean(change_ratio))
# change_ratio_IA$Site <- ID
# change_ratio_IA$Survey_time <- t
# change_ratio_IA$Stage <- "IA"
# 
# change_ratio_CA <- dynamics_df_CA %>% 
#   group_by(dynamic) %>% 
#   summarize(ratio = mean(change_ratio))
# change_ratio_CA$Site <- ID
# change_ratio_CA$Survey_time <- t
# change_ratio_CA$Stage <- "CA"
#   
# change_ratio_df <- rbind(change_ratio_df, change_ratio_J,change_ratio_IA,change_ratio_CA)
# }
# }

# 
# 
# 
dynamics_df$ratio_ad <-  ifelse(dynamics_df$Survey_time == 1 & dynamics_df$Site == "M1",
                                    dynamics_df$change_ratio * 12/17,
                                    ifelse(
                                    dynamics_df$Survey_time == 2 & dynamics_df$Site == "M1",
                                    dynamics_df$change_ratio * 12/9,
                                    ifelse(
                                    dynamics_df$Survey_time == 1 & dynamics_df$Site == "M2",
                                    dynamics_df$change_ratio * 12/15,
                                    ifelse(
                                    dynamics_df$Survey_time == 2 & dynamics_df$Site == "M2",
                                    dynamics_df$change_ratio * 12/11,
                                    ifelse(
                                    dynamics_df$Survey_time == 1 & dynamics_df$Site == "TY3",
                                    dynamics_df$change_ratio * 12/18,
                                    ifelse(
                                    dynamics_df$Survey_time == 2 & dynamics_df$Site == "TY3",
                                    dynamics_df$change_ratio * 12/8,
                                    dynamics_df$change_ratio
                                    )
                                    )
                                    )
                                    )
                                    )
)


### Calculate mean change ratio in each stage
dynamics_df_J <- filter(dynamics_df, pure_size == "S" )#& Survey_times == 2)
dynamics_df_IA <- filter(dynamics_df, pure_size == "M") #& Survey_times == 2 )
dynamics_df_CA <- filter(dynamics_df, pure_size == "L")  #& Survey_times == 2)

change_ratio_J <- dynamics_df_J %>%
  group_by(dynamic_p) %>%
  summarize(mean_x = mean(ratio_ad), count = n())

change_ratio_IA <- dynamics_df_IA %>%
  group_by(dynamic_p) %>%
  summarize(mean_x = mean(ratio_ad), count = n())

change_ratio_CA <- dynamics_df_CA %>%
  group_by(dynamic_p) %>%
  summarize(mean_x = mean(ratio_ad), count = n())

# 
# #filter(Change_ratio_df,dynamic == "FuIA" & dynamic == "J") #WTF it is not working?????
# a <- change_ratio_df[change_ratio_df$dynamic=="GJ" &!is.na(change_ratio_df$dynamic),]
# a
# mean(a$ratio)
```


```{r}
### calculate change ratio of area between each stage
dynamics_df_J <- filter(dynamics_df, pure_size == "S" )#& Survey_times == 2) #& Survey_times == t
dynamics_df_IA <- filter(dynamics_df, pure_size == "M")# & Survey_times == 2)
dynamics_df_CA <- filter(dynamics_df, pure_size == "L")# & Survey_times == 2)

# calculate for J
total_area_J <- sum(dynamics_df_J$area)
dynamic_J <- dynamics_df_J %>% 
  group_by(dynamic_p) %>% 
  summarize(sum_area = sum(area), N=n())
# temp <- dynamics_df_J %>% 
#   group_by(dynamic) %>% 
#   summarize(dynamic_sum = sum(sa_change))
dynamic_J$sum_ratio <- dynamic_J$sum_area / total_area_J
#dynamic_J$dynamic_sum <- temp$dynamic_sum
# dynamic_J$dynamic_ratio <- dynamic_J$dynamic_sum / total_area_J
# dynamic_J$gross_ratio <- dynamic_J$sum_ratio + dynamic_J$dynamic_ratio
# dynamic_J$sum_ratio <- round(dynamic_J$sum_ratio, digits = 3)
# dynamic_J$dynamic_ratio <- round(dynamic_J$dynamic_ratio, digits = 3)
# dynamic_J$gross_ratio <- round(dynamic_J$gross_ratio, digits = 3)


# calculate for IA
total_area_IA <- sum(dynamics_df_IA$area)
dynamic_IA <- dynamics_df_IA %>% 
  group_by(dynamic_p) %>% 
  summarize(sum_area = sum(area), N=n())
# temp <- dynamics_df_IA %>% 
#   group_by(dynamic) %>% 
#   summarize(dynamic_sum = sum(sa_change), N=n())
dynamic_IA$sum_ratio <- dynamic_IA$sum_area / total_area_IA
# dynamic_IA$dynamic_sum <- temp$dynamic_sum
# dynamic_IA$dynamic_ratio <- dynamic_IA$dynamic_sum / total_area_IA
# dynamic_IA$gross_ratio <- dynamic_IA$sum_ratio + dynamic_IA$dynamic_ratio
# dynamic_IA$sum_ratio <- round(dynamic_IA$sum_ratio, digits = 3)
# dynamic_IA$dynamic_ratio <- round(dynamic_IA$dynamic_ratio, digits = 3)
# dynamic_IA$gross_ratio <- round(dynamic_IA$gross_ratio, digits = 3)


# calculate for CA
total_area_CA <- sum(dynamics_df_CA$area)
dynamic_CA <- dynamics_df_CA %>% 
  group_by(dynamic_p) %>% 
  summarize(sum_area = sum(area), N=n())
# temp <- dynamics_df_CA %>% 
#   group_by(dynamic) %>% 
#   summarize(dynamic_sum = sum(sa_change), N=n())
 dynamic_CA$sum_ratio <- dynamic_CA$sum_area / total_area_CA
# dynamic_CA$dynamic_sum <- temp$dynamic_sum
# dynamic_CA$dynamic_ratio <- dynamic_CA$dynamic_sum / total_area_CA
# dynamic_CA$gross_ratio <- dynamic_CA$sum_ratio + dynamic_CA$dynamic_ratio
# dynamic_CA$sum_ratio <- round(dynamic_CA$sum_ratio, digits = 3)
# dynamic_CA$dynamic_ratio <- round(dynamic_CA$dynamic_ratio, digits = 3)
# dynamic_CA$gross_ratio <- round(dynamic_CA$gross_ratio, digits = 3)

## calculate for recruitment
recruit_t1 <- filter(pa_data_done, Recruit == "Y" & Survey_times == 2)
IA_t1 <- filter(pa_data_done, pure_size == "M" & Survey_times == 1)
CA_t1 <- filter(pa_data_done, pure_size == "L" & Survey_times == 1)
recruit_t2 <- filter(pa_data_done, Recruit == "Y" & Survey_times == 3)
IA_t2 <- filter(pa_data_done, pure_size == "M" & Survey_times == 2)
CA_t2 <- filter(pa_data_done, pure_size == "L" & Survey_times == 2)

sum_r_t1 <- sum(recruit_t1$Shape_Area)
sum_IA_t1 <- sum(IA_t1$Shape_Area)
sum_CA_t1 <- sum(CA_t1$Shape_Area)

sum_r_t2 <- sum(recruit_t2$Shape_Area)
sum_IA_t2 <- sum(IA_t2$Shape_Area)
sum_CA_t2 <- sum(CA_t2$Shape_Area)

# assume 1/2 recruit from IA and 1/2 from CA

R_IA_t1 <- (1/2*sum_r_t1) / sum_IA_t1
R_CA_t1 <- (1/2*sum_r_t1) / sum_CA_t1

R_IA_t2 <- (1/2*sum_r_t2) / sum_IA_t2
R_CA_t2 <- (1/2*sum_r_t2) / sum_CA_t2

(R_IA_t1 + R_IA_t2) /2
(R_CA_t1 + R_CA_t2) /2
```

```{r}
recruit_t1 <- filter(pa_data_done, Recruit == "Y" & Survey_times == 2)
IA_t1 <- filter(pa_data_done, size_class == "IA" & Survey_times == 1)
CA_t1 <- filter(pa_data_done, size_class == "CA" & Survey_times == 1)
recruit_t2 <- filter(pa_data_done, Recruit == "Y" & Survey_times == 3)
IA_t2 <- filter(pa_data_done, size_class == "IA" & Survey_times == 2)
CA_t2 <- filter(pa_data_done, size_class == "CA" & Survey_times == 2)

sum_r_t1 <- sum(recruit_t1$Shape_Area)
sum_IA_t1 <- sum(IA_t1$Shape_Area)
sum_CA_t1 <- sum(CA_t1$Shape_Area)

sum_r_t2 <- sum(recruit_t2$Shape_Area)
sum_IA_t2 <- sum(IA_t2$Shape_Area)
sum_CA_t2 <- sum(CA_t2$Shape_Area)

(sum_r_t1 / (sum_IA_t1 + sum_CA_t1)) * 12/15 # T1 recruit (proportion of adult)
(sum_r_t2 / (sum_IA_t2 + sum_CA_t2)) * 12/9
```


```{r catagorize size }
pa_data_done$size[pa_data_done$Shape_Area< 0.03*0.03*pi ] <- 'J' #Diameter smaller than 6 cm is juvenile
pa_data_done$size[pa_data_done$Shape_Area>= 0.03*0.03*pi & pa_data_done$Shape_Area <= 0.05*0.05*pi] <- 'M' #Diameter smaller than 10 cm is Middle
pa_data_done$size[pa_data_done$Shape_Area> 0.05*0.05*pi ] <- 'L' #Diameter larger than 10 cm is Large

# Classify the count base on diameter
pa_data_done$size_str[pa_data_done$Shape_Area<= 0.01*0.01*pi ] <- '0~2' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.01*0.01*pi & pa_data_done$Shape_Area <= 0.02*0.02*pi] <- '2~4' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.02*0.02*pi & pa_data_done$Shape_Area <= 0.03*0.03*pi] <- '4~6' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.03*0.03*pi & pa_data_done$Shape_Area <= 0.04*0.04*pi] <- '6~8' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.04*0.04*pi & pa_data_done$Shape_Area <= 0.05*0.05*pi] <- '8~10' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.05*0.05*pi & pa_data_done$Shape_Area <= 0.06*0.06*pi] <- '10~12' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.06*0.06*pi & pa_data_done$Shape_Area <= 0.07*0.07*pi] <- '12~14' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.07*0.07*pi & pa_data_done$Shape_Area <= 0.08*0.08*pi] <- '14~16'
pa_data_done$size_str[pa_data_done$Shape_Area> 0.08*0.08*pi & pa_data_done$Shape_Area <= 0.09*0.09*pi] <- '16~18' 
pa_data_done$size_str[pa_data_done$Shape_Area> 0.09*0.09*pi & pa_data_done$Shape_Area <= 0.10*0.10*pi] <- '18~20'
pa_data_done$size_str[pa_data_done$Shape_Area> 0.10*0.10*pi ] <- '>20' 
pa_data_done$size_str <- as.factor(pa_data_done$size_str)

# Calculate number of J, M, L 
count_J <- sum(grepl("J", pa_data_done_3$size))
count_M <- sum(grepl("M", pa_data_done_3$size))
count_L <- sum(grepl("L", pa_data_done_3$size))
count_size <- data.frame(size = c("J","M","L"),
                         count= c(count_J,count_M,count_L))
```

```{r}

# Count the number of occurrences of each category in the size_str column
counts <- table(pa_data_done$size_str)

# Create a data frame with the counts and the category names
df <- as.data.frame(counts)
myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

# Classify the count base on diameter
df$size <- case_when(
  df$Var1 == "0~2" ~ "S",
  df$Var1 == "2~4" ~ "S",
  df$Var1 == "4~6" ~ "S",
  df$Var1 == "6~8" ~ "M",
  df$Var1 == "8~10" ~ "M",
  df$Var1 == "10~12" ~ "M",
  df$Var1 == "12~14" ~ "L",
  df$Var1 == "14~16" ~ "L",
  df$Var1 == "16~18" ~ "L",
  df$Var1 == "18~20" ~ "L",
  df$Var1 == ">20" ~ "L",
  TRUE ~ NA_character_
)

# Create the barplot
ggplot(df, aes(x = Var1, y = Freq,fill = size)) +
  geom_bar(stat = "identity") +
  labs(x = "Size", y = "Count")+
  scale_fill_manual(values = c("S" = "steelblue", "M" = "chartreuse", "L"="coral"))
```

```{r}
ggplot(pa_data_done, aes(x = size_str, y = Freq,fill = size)) 


```


```{r size and counts}
# Detect limitation

pa_data_done_1 <- filter(pa_data_done, Survey_times == 1)
pa_data_done_2 <- filter(pa_data_done, Survey_times == 2)
pa_data_done_3 <- filter(pa_data_done, Survey_times == 3)

ggplot(pa_data_done_3, aes(x=Shape_Area)) + geom_histogram(bins = 60)

# Detect limitation
data <- filter(pa_data_done, Survey_times==2)
ggplot(data, aes(x=log10(Shape_Area))) + geom_histogram(aes(y=..density..),bins = 60)+ 
  geom_density()+ ylim(0,1.5)

# Classify the count base on diameter

```

```{r}
###### Size
df_J <- filter(pa_data_done, pure_size=="S" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, pure_size=="M")#& Survey_times == 3)
df_CA <- filter(pa_data_done, pure_size=="L")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$pure_size <- "S" 
df_IA <- as.data.frame(counts_IA)
df_IA$pure_size <- "M" 
df_CA <- as.data.frame(counts_CA)
df_CA$pure_size <- "L" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=pure_size, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")

###### PA ratio
df_J <- filter(pa_data_done, size_class=="J" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, size_class=="IA")#& Survey_times == 3)
df_CA <- filter(pa_data_done, size_class=="CA")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$size_class <- "J" 
df_IA <- as.data.frame(counts_IA)
df_IA$size_class <- "IA" 
df_CA <- as.data.frame(counts_CA)
df_CA$size_class <- "CA" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=size_class, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")

###### Circularity
df_J <- filter(pa_data_done, size_class_circ=="J" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, size_class_circ=="IA")#& Survey_times == 3)
df_CA <- filter(pa_data_done, size_class_circ=="CA")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$size_class_circ <- "J" 
df_IA <- as.data.frame(counts_IA)
df_IA$size_class_circ <- "IA" 
df_CA <- as.data.frame(counts_CA)
df_CA$size_class_circ <- "CA" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=size_class_circ, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")


###### PA ratio x
df_J <- filter(pa_data_done, pa_ratio_x=="J" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, pa_ratio_x=="IA")#& Survey_times == 3)
df_CA <- filter(pa_data_done, pa_ratio_x=="CA")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$pa_ratio_x <- "J" 
df_IA <- as.data.frame(counts_IA)
df_IA$pa_ratio_x <- "IA" 
df_CA <- as.data.frame(counts_CA)
df_CA$pa_ratio_x <- "CA" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=pa_ratio_x, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")



###### PA ratio xx
df_J <- filter(pa_data_done, pa_ratio_xx=="J" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, pa_ratio_xx=="IA")#& Survey_times == 3)
df_CA <- filter(pa_data_done, pa_ratio_xx=="CA")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$pa_ratio_xx <- "J" 
df_IA <- as.data.frame(counts_IA)
df_IA$pa_ratio_xx <- "IA" 
df_CA <- as.data.frame(counts_CA)
df_CA$pa_ratio_xx <- "CA" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=pa_ratio_xx, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")

# ###### Medien size
# df_J <- filter(pa_data_done, size_class_size=="J" )#& Survey_times == 3)
# df_IA <- filter(pa_data_done, size_class_size=="M")#& Survey_times == 3)
# df_CA <- filter(pa_data_done, size_class_size=="L")#& Survey_times == 3)
# 
# # Count the number of occurrences of each category in the size_str column
# counts_J <- table(df_J$size_str)
# counts_IA <- table(df_IA$size_str)
# counts_CA <- table(df_CA$size_str)
# 
# # Create a data frame with the counts and the category names
# df_J <- as.data.frame(counts_J)
# df_J$size_class_size <- "J" 
# df_IA <- as.data.frame(counts_IA)
# df_IA$size_class_size <- "M" 
# df_CA <- as.data.frame(counts_CA)
# df_CA$size_class_size <- "L" 
# df <- rbind(df_J,df_IA,df_CA)
# 
# myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
# df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))
# 
# ggplot(df, aes(fill=size_class_size, y=Freq, x=Var1))+
#   geom_bar(position = "stack", stat = "identity")

# medien P/A ratio
df_J <- filter(pa_data_done, size_class_pa=="J" )#& Survey_times == 3)
df_IA <- filter(pa_data_done, size_class_pa=="IA")#& Survey_times == 3)
df_CA <- filter(pa_data_done, size_class_pa=="CA")#& Survey_times == 3)

# Count the number of occurrences of each category in the size_str column
counts_J <- table(df_J$size_str)
counts_IA <- table(df_IA$size_str)
counts_CA <- table(df_CA$size_str)

# Create a data frame with the counts and the category names
df_J <- as.data.frame(counts_J)
df_J$size_class_pa <- "J" 
df_IA <- as.data.frame(counts_IA)
df_IA$size_class_pa <- "IA" 
df_CA <- as.data.frame(counts_CA)
df_CA$size_class_pa <- "CA" 
df <- rbind(df_J,df_IA,df_CA)

myorder <-c("0~2", "2~4", "4~6","6~8","8~10","10~12","12~14","14~16","16~18","18~20",">20")
df$Var1 <- reorder(df$Var1, match(df$Var1, myorder))

ggplot(df, aes(fill=size_class_pa, y=Freq, x=Var1))+
  geom_bar(position = "stack", stat = "identity")



```

